name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run tests
          run: cargo test --lib
          
  clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run clippy
          run: cargo clippy --all -- -D warnings
          
  fmt:
        name: Fmt
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run fmt
          run: cargo fmt --all -- --check

  integration-tests:
        name: Integration tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Install Nemo
          run: cargo install --path .
        - name: Run integration tests
          run: cargo test --test_nemo
